package model.mwgl.eo;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 22 06:49:52 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderItemsDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OrderItemsDefImpl() {
    }
}
