package model.mwgl.eo;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 22 06:41:55 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdersDefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OrdersDefImpl() {
    }
}
