package model.mwgl.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 22 06:49:52 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderItemsImpl extends EntityImpl {
    private static OrderItemsDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OrderId {
            public Object get(OrderItemsImpl obj) {
                return obj.getOrderId();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setOrderId((Number)value);
            }
        }
        ,
        LineItemId {
            public Object get(OrderItemsImpl obj) {
                return obj.getLineItemId();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setLineItemId((Number)value);
            }
        }
        ,
        ProductId {
            public Object get(OrderItemsImpl obj) {
                return obj.getProductId();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setProductId((Number)value);
            }
        }
        ,
        Quantity {
            public Object get(OrderItemsImpl obj) {
                return obj.getQuantity();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setQuantity((Integer)value);
            }
        }
        ,
        UnitPrice {
            public Object get(OrderItemsImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(OrderItemsImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OrderItemsImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OrderItemsImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OrderItemsImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(OrderItemsImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setObjectVersionId((Number)value);
            }
        }
        ,
        ListPrice {
            public Object get(OrderItemsImpl obj) {
                return obj.getListPrice();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setListPrice((Number)value);
            }
        }
        ,
        Orders {
            public Object get(OrderItemsImpl obj) {
                return obj.getOrders();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setOrders((OrdersImpl)value);
            }
        }
        ,
        ProductsBase {
            public Object get(OrderItemsImpl obj) {
                return obj.getProductsBase();
            }

            public void put(OrderItemsImpl obj, Object value) {
                obj.setProductsBase((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OrderItemsImpl object);

        public abstract void put(OrderItemsImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ORDERID = AttributesEnum.OrderId.index();
    public static final int LINEITEMID = AttributesEnum.LineItemId.index();
    public static final int PRODUCTID = AttributesEnum.ProductId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int LISTPRICE = AttributesEnum.ListPrice.index();
    public static final int ORDERS = AttributesEnum.Orders.index();
    public static final int PRODUCTSBASE = AttributesEnum.ProductsBase.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OrderItemsImpl() {
    }

    /**
     * Gets the attribute value for OrderId, using the alias name OrderId.
     * @return the OrderId
     */
    public Number getOrderId() {
        return (Number)getAttributeInternal(ORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderId.
     * @param value value to set the OrderId
     */
    public void setOrderId(Number value) {
        setAttributeInternal(ORDERID, value);
    }

    /**
     * Gets the attribute value for LineItemId, using the alias name LineItemId.
     * @return the LineItemId
     */
    public Number getLineItemId() {
        return (Number)getAttributeInternal(LINEITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineItemId.
     * @param value value to set the LineItemId
     */
    public void setLineItemId(Number value) {
        setAttributeInternal(LINEITEMID, value);
    }

    /**
     * Gets the attribute value for ProductId, using the alias name ProductId.
     * @return the ProductId
     */
    public Number getProductId() {
        return (Number)getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductId.
     * @param value value to set the ProductId
     */
    public void setProductId(Number value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the Quantity
     */
    public Integer getQuantity() {
        return (Integer)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Integer value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for UnitPrice, using the alias name UnitPrice.
     * @return the UnitPrice
     */
    public Number getUnitPrice() {
        return (Number)getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPrice.
     * @param value value to set the UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ObjectVersionId, using the alias name ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Number getObjectVersionId() {
        return (Number)getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObjectVersionId.
     * @param value value to set the ObjectVersionId
     */
    public void setObjectVersionId(Number value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * Gets the attribute value for ListPrice, using the alias name ListPrice.
     * @return the ListPrice
     */
    public Number getListPrice() {
        return (Number)getAttributeInternal(LISTPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ListPrice.
     * @param value value to set the ListPrice
     */
    public void setListPrice(Number value) {
        setAttributeInternal(LISTPRICE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity OrdersImpl.
     */
    public OrdersImpl getOrders() {
        return (OrdersImpl)getAttributeInternal(ORDERS);
    }

    /**
     * Sets <code>value</code> as the associated entity OrdersImpl.
     */
    public void setOrders(OrdersImpl value) {
        setAttributeInternal(ORDERS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getProductsBase() {
        return (EntityImpl)getAttributeInternal(PRODUCTSBASE);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setProductsBase(EntityImpl value) {
        setAttributeInternal(PRODUCTSBASE, value);
    }

    /**
     * @param orderId key constituent
     * @param lineItemId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number orderId, Number lineItemId) {
        return new Key(new Object[]{orderId, lineItemId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (OrderItemsDefImpl)EntityDefImpl.findDefObject("model.mwgl.eo.OrderItems");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
