package model.mwgl.vo.common;

import oracle.jbo.JboException;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 05 06:11:39 IST 2022
// ---------------------------------------------------------------------
public interface OrdersView extends ViewObject {
    void cancelOrder() throws JboException;
}
