package model.mwgl.vo.client;

import model.mwgl.vo.common.OrdersView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 05 06:11:39 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdersViewClient extends ViewUsageImpl implements OrdersView {
    /**
     * This is the default constructor (do not remove).
     */
    public OrdersViewClient() {
    }

    public void cancelOrder() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"cancelOrder",null,null);
        return;
    }
}
